services:
  - type: web
    name: wow-english-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python cloud_run.py
    healthCheckPath: /
    autoDeploy: true
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: GEMINI_API_KEY
        sync: false
